require 'rbconfig'
# ruby 1.8.7 doesn't define RUBY_ENGINE
ruby_engine = defined?(RUBY_ENGINE) ? RUBY_ENGINE : 'ruby'
ruby_version = RbConfig::CONFIG["ruby_version"]
path = File.expand_path('..', __FILE__)
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/i18n-0.7.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/json-1.8.3/Users/treeder/Google Drive/dev/slackin/bundle/ruby/2.1.0/extensions/x86_64-darwin-14/2.1.0/json-1.8.3"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/json-1.8.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/minitest-5.7.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/thread_safe-0.3.5/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/tzinfo-1.2.2/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/activesupport-4.2.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/addressable-2.3.8/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/extlib-0.9.16/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/multi_json-1.11.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/autoparse-0.3.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/unf_ext-0.0.7.1/Users/treeder/Google Drive/dev/slackin/bundle/ruby/2.1.0/extensions/x86_64-darwin-14/2.1.0/unf_ext-0.0.7.1"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/unf_ext-0.0.7.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/unf-0.1.4/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/domain_name-0.5.24/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/eventmachine-1.0.7/Users/treeder/Google Drive/dev/slackin/bundle/ruby/2.1.0/extensions/x86_64-darwin-14/2.1.0/eventmachine-1.0.7"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/eventmachine-1.0.7/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/multipart-post-2.0.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/faraday-0.9.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/faraday_middleware-0.9.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/websocket-extensions-0.1.2/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/websocket-driver-0.5.4/Users/treeder/Google Drive/dev/slackin/bundle/ruby/2.1.0/extensions/x86_64-darwin-14/2.1.0/websocket-driver-0.5.4"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/websocket-driver-0.5.4/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/faye-websocket-0.9.2/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/jwt-1.5.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/little-plugger-1.1.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/logging-2.0.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/memoist-0.12.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/signet-0.6.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/googleauth-0.4.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/launchy-2.4.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/retriable-1.4.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/google-api-client-0.8.6/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/http-cookie-1.0.2/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/mime-types-2.6.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/net-http-persistent-2.9.4/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/netrc-0.10.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/rack-1.6.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/puma-2.11.3/Users/treeder/Google Drive/dev/slackin/bundle/ruby/2.1.0/extensions/x86_64-darwin-14/2.1.0/puma-2.11.3"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/puma-2.11.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/rack-protection-1.5.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/rest-3.0.6/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/rest-client-1.8.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/tilt-2.0.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/sinatra-1.4.6/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/slack-api-1.1.6/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/stripe-1.22.0/lib"
